const keyTypes = ({
  CHANGE_TARGET_COLUMN: 'CHANGE_TARGET_COLUMN',
  CHANGE_TARGET_FIELD: 'CHANGE_TARGET_FIELD',
  DROP_COUNTER: 'DROP_COUNTER',
  CHANGE_PLAYER: 'CHANGE_PLAYER',
})

export default keyTypes
